[package]
name = "crucible-client-types"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.0"
schemars = { version = "0.8.11", features = [ "uuid1" ] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.2.2", features = [ "serde", "v4" ] }
