[package]
name = "crucible-for-clients"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
schemars = { version = "0.8.10", features = [ "uuid1" ] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.0.0", features = [ "serde", "v4" ] }
