[package]
name = "crucible-pantry"
version = "0.0.1"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21"
chrono = { version = "0.4", features = [ "serde" ] }
clap = { version = "4.3", features = ["derive"] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
futures = "0.3"
http = "0.2.9"
hyper = "0.14"
schemars = { version = "0.8", features = [ "chrono", "uuid1" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
slog = { version = "2.7", features = [ "max_level_trace", "release_max_level_debug" ] }
crucible = { path = "../upstairs" }
crucible-common = { path = "../common" }
crucible-smf = { path = "../smf" }
omicron-common = { git = "https://github.com/oxidecomputer/omicron", branch = "main" }
tokio = { version = "1.28", features = [ "full" ] }
uuid = { version = "1.3.3", features = [ "serde", "v4" ] }
reqwest = { version = "0.11", features = ["json", "stream"] }
hex = "0.4"
sha2 = "0.10"

[dev-dependencies]
expectorate = "1.0.7"
openapiv3 = "1.0"
openapi-lint = { git = "https://github.com/oxidecomputer/openapi-lint", branch = "main" }
subprocess = "0.2.9"
