[package]
name = "crucible-pantry"
version = "0.0.1"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
dropshot.workspace = true
futures.workspace = true
http.workspace = true
hyper.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
crucible.workspace = true
crucible-common.workspace = true
crucible-smf.workspace = true
omicron-common.workspace = true
tokio.workspace = true
uuid.workspace = true
reqwest.workspace = true
hex.workspace = true
sha2.workspace = true
crucible-workspace-hack.workspace = true

[dev-dependencies]
expectorate.workspace = true
openapi-lint.workspace = true
openapiv3.workspace = true
subprocess.workspace = true
