[package]
name = "crucible-protocol"
version = "0.0.0"
authors = ["Joshua M. Clulow <jmc@oxide.computer>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bytes.workspace = true
clap.workspace = true
crucible-common.workspace = true
futures.workspace = true
num_enum.workspace = true
schemars.workspace = true
serde.workspace = true
tokio-util.workspace = true
tokio.workspace = true
uuid.workspace = true
statistical.workspace = true
