[package]
name = "crucible-protocol"
version = "0.0.0"
authors = ["Joshua M. Clulow <jmc@oxide.computer>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
tokio-util = { version = "0.7", features = [ "codec" ] }
bytes = { version = "1", features = ["serde"] }
anyhow = "1"
crucible-common = { path = "../common" }
serde = "1.0"
bincode = "1.3.3"
num_enum = "0.6"
uuid = { version = "1.3.2", features = [ "serde", "v4" ] }
