[package]
name = "crucible-package"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
omicron-zone-package.workspace = true
tokio.workspace = true
crucible-workspace-hack = { version = "0.1", path = "../workspace-hack" }
